version: "3.8"

services:
  database:
    image: mongo
    container_name: coffeedatabase
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - coffeedatabasecontainer:/data/db

volumes:
  coffeedatabasecontainer:
